// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import models "github.com/smartcontractkit/chainlink/core/store/models"

// JobExecutor is an autogenerated mock type for the JobExecutor type
type JobExecutor struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *JobExecutor) Execute(_a0 *models.ID) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
